#!/bin/bash -e
cd $(dirname $0)
PATH=$HOME/gopath/bin:$GOPATH/bin:$PATH

function announce
{
  echo
  echo $@
}

function v
{
  announce $@
  $@
}

if ! type -p goveralls; then
  v go get github.com/mattn/goveralls
fi

if ! type -p shadow; then
  v go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
fi

if ! type -p goreturns; then
  v go install github.com/sqs/goreturns
fi

v goreturns -l -w *.go

v go test -v -covermode=count -coverprofile=cover.out .
v go tool cover -func=cover.out
[ -z "$COVERALLS_TOKEN" ] || goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
rm cover.out

v go vet .
v shadow .
